services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-demo
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped

  livereload:
    build:
      context: .
      dockerfile: Dockerfile.livereload
    volumes:
      - ./html:/app/src
    ports:
      - "35729:35729"